### ISSUE TITLE
大佬，train脚本中103行的数据集换成CIFAR报错

### ISSUE THREAD

**Issue by zaneoo** [Lornatang/GAN-PyTorch#3]
这是我的报错信息
D:\Anaconda\envs\pytorch_g\python.exe D:/pyvscodeprograms/GAN_program/Lornatang_style/GAN-PyTorch/train.py
Files already downloaded and verified
Traceback (most recent call last):
  File "D:/pyvscodeprograms/GAN_program/Lornatang_style/GAN-PyTorch/train.py", line 139, in <module>
    main()
  File "D:/pyvscodeprograms/GAN_program/Lornatang_style/GAN-PyTorch/train.py", line 121, in main
    train(dataloader, epoch)
  File "D:/pyvscodeprograms/GAN_program/Lornatang_style/GAN-PyTorch/train.py", line 53, in train
    d_loss_real.backward()
  File "D:\Anaconda\envs\pytorch_g\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\Anaconda\envs\pytorch_g\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function AddmmBackward returned an invalid gradient at index 2 - got [3072, 512] but expected shape compatible with [784, 512]

Process finished with exit code 1

我应该怎么改这个错误呢？是模型dim问题吗
另外，一般对于自己的数据集batch size设置为多少合适

**Comment by Lornatang** [comment]
应该有其他几个问题，首先`train.py`中107行改为transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]),
然后模型文件中Generator首层输入由1改成3，Discriminator也需要相应更改。
如果你觉得上述修改比较复杂，将CIFAR改为灰度图输出然后缩放至28x28就好了
